language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
env:
  - RUST_LOG=trace
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --example gallery
  - cargo run --example inspect
  - cargo run --example walk
  - cargo fmt -- --check
cache: cargo
git:
  depth: 3
