language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
env:
  - RUST_LOG=trace
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run --example query
  - cargo run --example pipeline
  - cargo run --example sampler-state
  - cargo run --example walk
  - cargo run --example spirv-spec
#  - cargo fmt -- --check
cache: cargo
git:
  depth: 3
